In [16]:
import numpy as np

In [15]:
print(np.__version__)

2.1.0


In [5]:
# create a null vector of size 10
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# itemsize returns length of array elements in bytes. 
# itemsize returns the per-element and does not depend on the number of elements in the array.
# size returns number of elemenys in array.
# find the memory size of any array.

array_1 = np.array([1, 2, 3])
print(f"itemsize:", array_1.itemsize)
print(f"size:", array_1.size)

itemsize: 8
size: 3


In [17]:
# get docs of `add` function
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [22]:
# create a null vector with 5th element as 10
array_2 = np.zeros(5)
array_2[4] = 10
print(f"array with default dtype of float64: ", array_2)
array_3 = np.zeros(5, dtype=np.int64)
array_3[4] = 10
print(f"array with specified dtype of int64: ", array_3)

array with default dtype of float64:  [ 0.  0.  0.  0. 10.]
array with specified dtype of int64:  [ 0  0  0  0 10]


In [27]:
# create vector with values ranging from 10 to 49
array_4 = np.arange(10, 49)
print(array_4)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [28]:
# reverse a vector 
array_4[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [35]:
# create a array of 9 elements in a 3 x 3 matrix fashion
array_5 = np.arange(9).reshape((3, 3))
array_5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
# indices of non zero elements 
print(np.nonzero(np.array([1,2,0,0,4,0])))


(array([0, 1, 4]),)


In [37]:
# create a 3x3 identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
# 3x3x3 array with randome values 
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.0319584  0.58304295 0.45276375]
  [0.70323424 0.62780891 0.17640084]
  [0.48071535 0.63279605 0.64944463]]

 [[0.64263526 0.56084928 0.54151571]
  [0.12203141 0.0925441  0.22111354]
  [0.62542097 0.56194691 0.56996772]]

 [[0.31426311 0.29121149 0.75208975]
  [0.95439732 0.07851447 0.66549383]
  [0.26872874 0.54696997 0.71943216]]]


In [47]:
# 10x10 matrix with random value
arr = np.random.random((10, 10))
print(arr)
print(arr.min())
print(arr.max())

[[0.19014069 0.59503832 0.08664106 0.95356334 0.39329127 0.54132707
  0.60320345 0.93593637 0.65580849 0.65999178]
 [0.21303366 0.37174342 0.71610799 0.81763971 0.85341283 0.08765282
  0.16141392 0.0855683  0.83598941 0.36690202]
 [0.43684849 0.43929749 0.3199661  0.31125295 0.53641555 0.49618885
  0.15156727 0.19165624 0.52501708 0.22116054]
 [0.29495801 0.34051687 0.72758716 0.74494048 0.39244634 0.88994602
  0.22072203 0.58069823 0.32960722 0.84139705]
 [0.27062796 0.24799894 0.40231275 0.03340486 0.24363001 0.898768
  0.83908854 0.29268052 0.3992245  0.93794452]
 [0.86345111 0.20791049 0.00751821 0.38296529 0.77673633 0.12159687
  0.9576846  0.40643641 0.38677169 0.15051162]
 [0.91907787 0.34387314 0.37401978 0.15990975 0.66110769 0.12150038
  0.98373868 0.70028644 0.93613283 0.69566677]
 [0.60936143 0.3675396  0.88771975 0.4997005  0.98852639 0.00114523
  0.89780614 0.76621799 0.77643998 0.19663805]
 [0.12367677 0.01155185 0.46990751 0.85261645 0.26362397 0.0907658
  0.61989366 0.